# Site settings

author: Lucas
email: lucas04@lucas04.xyz
twitter_username: __Lucas04__
github_username:  Lucas04-nhr

head-title: Lucas04's Blog
title: Lucas04's Blog

baseurl: "/blog"    # the subpath of your site, "/blog"
url: ""

# footer 
description: "With swords comes shadow!"

favo: "With swords comes shadow!"
descrpt: "I feel I have grown immensely from my travels with you. If, one day, I finally manage to make my dreams a reality... I wonder, will you still be there by my side?"


#
# Build settings
#

#exclude: [vendor]

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  highlight: true
  auto_ids:  true

sass:
  style: compressed

permalink: /posts/:categories/:title.html

paginate: 7
#paginate_path: 'page/:num'

gems: [jekyll-paginate, jekyll-last-modified-at, jemoji]


#
# Custom
#

# Color
# All css class, see: http://materializecss.com/color.html
header-color: "indigo lighten-1"
head-theme-color: "#5c6bc0"     # MUST in hex format, may the same as header-color. This color is for android chrome browser.

footer-color: "indigo lighten-1"
footer-button-color: "indigo lighten-2"
footer-link-color: "red-text text-accent-1"

share-button-color: "pink"
share-button-small-color: ""


##
#excerpt_separator: <!-- excerpt_end -->       # for post.excerpt

