allowBuilds:
  core-js: true
  esbuild: true
minimumReleaseAgeExclude:
  - '@vuepress-plume/plugin-fonts@1.0.0-rc.203 || 1.0.0-rc.204 || 1.0.0-rc.208'
  - '@vuepress-plume/plugin-search@1.0.0-rc.203 || 1.0.0-rc.204 || 1.0.0-rc.208'
  - vuepress-plugin-md-power@1.0.0-rc.203 || 1.0.0-rc.204 || 1.0.0-rc.208
  - vuepress-theme-plume@1.0.0-rc.203 || 1.0.0-rc.204 || 1.0.0-rc.208
overrides:
  webworkify-webpack: 2.1.5
